// <auto-generated />
using System;
using System.Collections.Generic;
using EldenRingSim.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EldenRingSim.Migrations
{
    [DbContext(typeof(EldenRingContext))]
    partial class EldenRingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EldenRingSim.DB.Ammo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ammos");
                });

            modelBuilder.Entity("EldenRingSim.DB.Armor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("EldenRingSim.DB.AshOfWar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Affinity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AshesOfWar");
                });

            modelBuilder.Entity("EldenRingSim.DB.BossStats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AverageDamage")
                        .HasColumnType("integer");

                    b.Property<bool>("BleedImmune")
                        .HasColumnType("boolean");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FireResist")
                        .HasColumnType("double precision");

                    b.Property<bool>("FrostImmune")
                        .HasColumnType("boolean");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<double>("HolyResist")
                        .HasColumnType("double precision");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LightningResist")
                        .HasColumnType("double precision");

                    b.Property<bool>("MadnessImmune")
                        .HasColumnType("boolean");

                    b.Property<double>("MagicResist")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PhysicalResist")
                        .HasColumnType("double precision");

                    b.Property<bool>("PoisonImmune")
                        .HasColumnType("boolean");

                    b.Property<bool>("ScarletRotImmune")
                        .HasColumnType("boolean");

                    b.Property<bool>("SleepImmune")
                        .HasColumnType("boolean");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Weakness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BossStats");
                });

            modelBuilder.Entity("EldenRingSim.DB.Bosses", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("EldenRingSim.DB.Classes", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("EldenRingSim.DB.Creatures", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("EldenRingSim.DB.Incantations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Slots")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Incantations");
                });

            modelBuilder.Entity("EldenRingSim.DB.Items", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObtainedFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EldenRingSim.DB.Locations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EldenRingSim.DB.NPCs", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("EldenRingSim.DB.Shields", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Shields");
                });

            modelBuilder.Entity("EldenRingSim.DB.Sorceries", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Slots")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorceries");
                });

            modelBuilder.Entity("EldenRingSim.DB.Spirits", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FpCost")
                        .HasColumnType("integer");

                    b.Property<int>("HpCost")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Spirits");
                });

            modelBuilder.Entity("EldenRingSim.DB.Talismans", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Talismans");
                });

            modelBuilder.Entity("EldenRingSim.DB.Weapons", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("EldenRingSim.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FavoriteBuild")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Playstyle")
                        .HasColumnType("text");

                    b.Property<string>("PsnId")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EldenRingSim.Models.BossFightAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BossFightSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BossId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DamageTaken")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PlayerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerProgressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Victory")
                        .HasColumnType("boolean");

                    b.Property<string>("WeaponUsedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponUsedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BossFightAttempts");
                });

            modelBuilder.Entity("EldenRingSim.Models.BossFightSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BossId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerProgressId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Victory")
                        .HasColumnType("boolean");

                    b.Property<int?>("VictoryAttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("VictoryWeaponId")
                        .HasColumnType("text");

                    b.Property<string>("VictoryWeaponName")
                        .HasColumnType("text");

                    b.Property<string>("WeaponsTriedIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BossFightSessions");
                });

            modelBuilder.Entity("EldenRingSim.Models.PlayerProgress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBuildId")
                        .HasColumnType("text");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRunes")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("DefeatedBossIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("DiscoveredGraceIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("GreatRunesCollected")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBeatenEldenBeast")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenFireGiant")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenGodrick")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenMalenia")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenMaliketh")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenMargit")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenMorgott")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeatenRadahn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("ObtainedWeaponIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PSN_ID")
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PlaytimeHours")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalDeaths")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("UnlockedRegions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("VisitedLocationIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EldenRingSim.DB.Ammo", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.AttackPowerEntry", "AttackPower", b1 =>
                        {
                            b1.Property<string>("AmmoId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AmmoId", "Id");

                            b1.ToTable("AttackPowerEntry");

                            b1.WithOwner()
                                .HasForeignKey("AmmoId");
                        });

                    b.Navigation("AttackPower");
                });

            modelBuilder.Entity("EldenRingSim.DB.Armor", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.NegationEntry", "DmgNegation", b1 =>
                        {
                            b1.Property<string>("ArmorId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ArmorId", "Id");

                            b1.ToTable("Armors_DmgNegation");

                            b1.WithOwner()
                                .HasForeignKey("ArmorId");
                        });

                    b.OwnsMany("EldenRingSim.DB.ResistanceEntry", "Resistance", b1 =>
                        {
                            b1.Property<string>("ArmorId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ArmorId", "Id");

                            b1.ToTable("ResistanceEntry");

                            b1.WithOwner()
                                .HasForeignKey("ArmorId");
                        });

                    b.Navigation("DmgNegation");

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("EldenRingSim.DB.AshOfWar", b =>
                {
                    b.OwnsOne("EldenRingSim.DB.AshOfWarDescription", "DescriptionDetails", b1 =>
                        {
                            b1.Property<string>("AshOfWarId")
                                .HasColumnType("text");

                            b1.Property<string>("DescriptionText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Effect")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AshOfWarId");

                            b1.ToTable("AshesOfWar");

                            b1.WithOwner()
                                .HasForeignKey("AshOfWarId");
                        });

                    b.Navigation("DescriptionDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("EldenRingSim.DB.Bosses", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.BossesDropEntry", "Drops", b1 =>
                        {
                            b1.Property<string>("BossesId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BossesId", "Id");

                            b1.ToTable("BossesDropEntry");

                            b1.WithOwner()
                                .HasForeignKey("BossesId");
                        });

                    b.Navigation("Drops");
                });

            modelBuilder.Entity("EldenRingSim.DB.Classes", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.StatEntry", "Stats", b1 =>
                        {
                            b1.Property<string>("ClassesId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ClassesId", "Id");

                            b1.ToTable("StatEntry");

                            b1.WithOwner()
                                .HasForeignKey("ClassesId");
                        });

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("EldenRingSim.DB.Creatures", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.CreaturesDropEntry", "Drops", b1 =>
                        {
                            b1.Property<string>("CreaturesId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CreaturesId", "Id");

                            b1.ToTable("CreaturesDropEntry");

                            b1.WithOwner()
                                .HasForeignKey("CreaturesId");
                        });

                    b.Navigation("Drops");
                });

            modelBuilder.Entity("EldenRingSim.DB.Incantations", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.IncantationsEffectEntry", "Effects", b1 =>
                        {
                            b1.Property<string>("IncantationsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IncantationsId", "Id");

                            b1.ToTable("IncantationsEffectEntry");

                            b1.WithOwner()
                                .HasForeignKey("IncantationsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.IncantationsRequirementEntry", "Requires", b1 =>
                        {
                            b1.Property<string>("IncantationsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IncantationsId", "Id");

                            b1.ToTable("IncantationsRequirementEntry");

                            b1.WithOwner()
                                .HasForeignKey("IncantationsId");
                        });

                    b.Navigation("Effects");

                    b.Navigation("Requires");
                });

            modelBuilder.Entity("EldenRingSim.DB.Items", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.ItemsEffectEntry", "Effect", b1 =>
                        {
                            b1.Property<string>("ItemsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ItemsId", "Id");

                            b1.ToTable("ItemsEffectEntry");

                            b1.WithOwner()
                                .HasForeignKey("ItemsId");
                        });

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("EldenRingSim.DB.Locations", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.SubLocationEntry", "SubLocations", b1 =>
                        {
                            b1.Property<string>("LocationsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LocationsId", "Id");

                            b1.ToTable("SubLocationEntry");

                            b1.WithOwner()
                                .HasForeignKey("LocationsId");
                        });

                    b.Navigation("SubLocations");
                });

            modelBuilder.Entity("EldenRingSim.DB.Shields", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.NegationEntry", "Attack", b1 =>
                        {
                            b1.Property<string>("ShieldsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ShieldsId", "Id");

                            b1.ToTable("Shields_Attack");

                            b1.WithOwner()
                                .HasForeignKey("ShieldsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.NegationEntry", "Defence", b1 =>
                        {
                            b1.Property<string>("ShieldsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ShieldsId", "Id");

                            b1.ToTable("Shields_Defence");

                            b1.WithOwner()
                                .HasForeignKey("ShieldsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.RequirementEntry", "RequiredAttributes", b1 =>
                        {
                            b1.Property<string>("ShieldsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ShieldsId", "Id");

                            b1.ToTable("Shields_RequiredAttributes");

                            b1.WithOwner()
                                .HasForeignKey("ShieldsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.ScalingEntry", "ScalesWith", b1 =>
                        {
                            b1.Property<string>("ShieldsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Scaling")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ShieldsId", "Id");

                            b1.ToTable("Shields_ScalesWith");

                            b1.WithOwner()
                                .HasForeignKey("ShieldsId");
                        });

                    b.Navigation("Attack");

                    b.Navigation("Defence");

                    b.Navigation("RequiredAttributes");

                    b.Navigation("ScalesWith");
                });

            modelBuilder.Entity("EldenRingSim.DB.Sorceries", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.SorceriesEffectEntry", "Effects", b1 =>
                        {
                            b1.Property<string>("SorceriesId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SorceriesId", "Id");

                            b1.ToTable("SorceriesEffectEntry");

                            b1.WithOwner()
                                .HasForeignKey("SorceriesId");
                        });

                    b.OwnsMany("EldenRingSim.DB.SorceriesRequirementEntry", "Requires", b1 =>
                        {
                            b1.Property<string>("SorceriesId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SorceriesId", "Id");

                            b1.ToTable("SorceriesRequirementEntry");

                            b1.WithOwner()
                                .HasForeignKey("SorceriesId");
                        });

                    b.Navigation("Effects");

                    b.Navigation("Requires");
                });

            modelBuilder.Entity("EldenRingSim.DB.Spirits", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.SpiritEffectEntry", "Effect", b1 =>
                        {
                            b1.Property<string>("SpiritsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpiritsId", "Id");

                            b1.ToTable("SpiritEffectEntry");

                            b1.WithOwner()
                                .HasForeignKey("SpiritsId");
                        });

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("EldenRingSim.DB.Weapons", b =>
                {
                    b.OwnsMany("EldenRingSim.DB.NegationEntry", "Attack", b1 =>
                        {
                            b1.Property<string>("WeaponsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WeaponsId", "Id");

                            b1.ToTable("Weapons_Attack");

                            b1.WithOwner()
                                .HasForeignKey("WeaponsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.NegationEntry", "Defence", b1 =>
                        {
                            b1.Property<string>("WeaponsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WeaponsId", "Id");

                            b1.ToTable("Weapons_Defence");

                            b1.WithOwner()
                                .HasForeignKey("WeaponsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.RequirementEntry", "RequiredAttributes", b1 =>
                        {
                            b1.Property<string>("WeaponsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WeaponsId", "Id");

                            b1.ToTable("Weapons_RequiredAttributes");

                            b1.WithOwner()
                                .HasForeignKey("WeaponsId");
                        });

                    b.OwnsMany("EldenRingSim.DB.ScalingEntry", "ScalesWith", b1 =>
                        {
                            b1.Property<string>("WeaponsId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Scaling")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WeaponsId", "Id");

                            b1.ToTable("Weapons_ScalesWith");

                            b1.WithOwner()
                                .HasForeignKey("WeaponsId");
                        });

                    b.Navigation("Attack");

                    b.Navigation("Defence");

                    b.Navigation("RequiredAttributes");

                    b.Navigation("ScalesWith");
                });

            modelBuilder.Entity("EldenRingSim.Models.PlayerProgress", b =>
                {
                    b.HasOne("EldenRingSim.Models.ApplicationUser", "User")
                        .WithMany("PlayerProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EldenRingSim.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EldenRingSim.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EldenRingSim.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EldenRingSim.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EldenRingSim.Models.ApplicationUser", b =>
                {
                    b.Navigation("PlayerProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
